### PR TITLE
Transparent logo added

### PR DESCRIPTION
**Pull request by khalidsaifullaah**

### CODE REVIEW

**Comment by pcuenca** [comment]
Sorry to nitpick, but why don't just the replace the previous one? Is there a reason for not doing it?

**Comment by khalidsaifullaah** [comment]
Oh, I didn't know if you guys may need it or something...
so I'm removing the previous one from the `img` directory then?

**Comment by pcuenca** [comment]
I would reuse the name and replace the file. That way README and the in-progress app don't need to change :)

**Comment by khalidsaifullaah** [comment]
I think things are in sync now!

**Pull request merged**
