### PR TITLE
Inferencing Colab

### PR DESCRIPTION
**Pull request by johnpaulbin**
Allows users to try out DALL-E Mini with ease.

### CODE REVIEW

**Comment by johnpaulbin** [comment]
Final fix. Github colab will be harder to maintain, so please link https://colab.research.google.com/drive/1vNB-4QIztaTxBVgju3dKNt372HaqtPr6 if needed! I will be focusing on the drive link more.

**Comment by borisdayma** [comment]
Thanks a lot for this PR.
Right now the repo is not stable as we're moving things around for our own demo but it should help make a more simple colab in a few days.

**Comment by johnpaulbin** [comment]
> Thanks a lot for this PR.
> Right now the repo is not stable as we're moving things around for our own demo but it should help make a more simple colab in a few days.

Good to hear eitherway, I'll keep updated inside this repo as things start to head into their "final state." I'll keep the colab maintained (my drive version) in the meantime.

**Comment by khalidsaifullaah** [comment]
> Allows users to try out DALL-E Mini with ease.

Tried out the Notebook, nicely done!
Thanks for making it @johnpaulbin😊

**Comment by johnpaulbin** [comment]
> > Allows users to try out DALL-E Mini with ease.
> 
> Tried out the Notebook, nicely done!
> Thanks for making it @johnpaulbin😊

Thank you! I'm looking forward with more model updates, would update the colab in a heartbeat!

**Comment by borisdayma** [comment]
Hey @johnpaulbin I'm gonna close it for now as we're making a simple inference notebook.
It should be merged today or tomorrow so then you can even simplify further your colab.

**Pull request closed without merging**
