### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by saharmor**
Added the DALL-E Playground repo to the readme

### CODE REVIEW

**Comment by saharmor** [comment]
Hey guys! I've been looking to build a playground for developers who are excited about DALL-E and started with using [Lucidrains' PyTorch version](https://github.com/lucidrains/DALLE-pytorch). Then I came across DALL-E Mini and after some tinkering, it seems to perform better and inferences were faster.

I thought it might be useful for others if I'd link to this repository here. I would also share it on HackerNews and other DL groups next week.

**Comment by borisdayma** [comment]
Hey, sorry for not replying earlier.
Your project looks great! I'm currently busy with the new version but thinking I could add a section for the cool projects using dalle-mini! Or maybe it will fit well somewhere near the inference colab.

**Comment by saharmor** [comment]
Sounds great, let me know if I can be of help.

**Comment by borisdayma** [comment]
Sorry for the delay @saharmor 
We finally were able to merge some major changes in the repo which should help scale better the model.
I need to retrain a small version of dalle-mini as the changes are not compatible with the existing checkpoints.
I can still go ahead and reference your repo but you should probably use a previous commit for now.

**Comment by saharmor** [comment]
No worries. Which commit includes the existing checkpoints? I'll pin it until we would change it to the updated model.

**Comment by borisdayma** [comment]
I added you to the README. Let me know if it looks good.

**Pull request closed without merging**
