### PR TITLE
doc(README): fix typos

### PR DESCRIPTION
**Pull request by SkiingIsFun123**
Small readability changes in the readme.md file

### CODE REVIEW

**Review by NomsterDude — APPROVED** [review]
Nothing that breaks the file, just some minor grammar editing. I see no problems here.

**Review by LorenzoQuiroz — APPROVED** [review]
LGTM

**Comment by borisdayma** [comment]
Thanks

**Comment by SkiingIsFun123** [comment]
Should I reopen it? Sorry I'm new to GitHub

**Comment by SkiingIsFun123** [comment]
I reopened it

**Pull request merged**
