### PR TITLE
chore: remove unused file

### PR DESCRIPTION
**Pull request by borisdayma**

### CODE REVIEW

**Comment by borisdayma** [comment]
@khalidsaifullaah @pcuenca Did we ever use `dataset.py`? I don't think so…
If it's not needed you can just merge this PR

**Comment by pcuenca** [comment]
We used it for the encoding of the CC12M dataset, see https://github.com/borisdayma/dalle-mini/blob/main/dev/notebooks/encoding/vqgan-jax-encoding-with-captions.ipynb, I only did minor modifications over Luke's contribution. I thought we would use it in later stages of the project, otherwise we could have just created the code inside the notebook.

**Comment by khalidsaifullaah** [comment]
Yeah, I've also used it as a reference for encoding of CC3M and YFCC, made slight modifications to Luke's code. I think if it's not too much of an issue we can keep it, as we've all used it to load our dataset. So, it may help others...?

**Comment by borisdayma** [comment]
Ok good to know!

**Pull request closed without merging**
