### PR TITLE
Update requirements for TPU support.

### PR DESCRIPTION
**Pull request by pcuenca**
This includes a complete installation as per the instructions in
https://github.com/huggingface/transformers/tree/master/examples/research_projects/jax-projects#tpu-vm

Note that `transformers` and `datasets` are installed from source,
in editable mode.

### CODE REVIEW

**Comment by borisdayma** [comment]
Awesome!

Quick questions:
- should we have something like `jax[tpu]>=0.2.16`
- you seem to have editable installs (one from your fork and one from Huggingface repo), should they both just reference the master branch of the git repo?

**Comment by pcuenca** [comment]
> * should we have something like `jax[tpu]>=0.2.16`

I see all versions have been pinned. I think you are right, it probably makes better sense to reference it that way.

> * you seem to have editable installs (one from your fork and one from Huggingface repo), should they both just reference the master branch of the git repo?

You are right. I followed the instructions provided by huggingface but shouldn't have submitted a link to my fork. Sorry about that, and thanks for noticing!

I'll make those changes and verify that everything works fine using a clean install in a new virtual environment. I'm in a train with a very poor connection right now, so I'll check in a few hours.

**Comment by pcuenca** [comment]
I created a much simpler requirements file without specifying package versions.

**Note**: you need to install using the following command:

```
$ pip install -r requirements.txt -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
```

Otherwise, pip won't be able to find the appropriate `libtpu_nightly`. I couldn't find a way to specify the `-f` option inside the requirements file itself.

**Comment by borisdayma** [comment]
Sorry just last questions:
* do we need the `-e` flag?
* can we put your instructions in the README?

**Comment by pcuenca** [comment]
> * do we need the `-e` flag?

I believe that the huggingface team was planning to merge new stuff during the sprint for additional JAX/Flax support and updated models. My understanding (but I might be wrong) is that an editable install would allow us to catch up with the latest version by simply pulling from the repo. If that's not correct, I can remove those flags, for sure.

> * can we put your instructions in the README?

Good call, just did it. I didn't touch anything about `conda`.

**Pull request merged**
